In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [3]:
data= pd.read_csv(r"C:\Users\mansi\Documents\LetsUpgrade\Day 25\train.csv")

In [5]:
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [16]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [21]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Cabin        202 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.5+ KB


In [25]:
data.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)
data.head()  #Dropiing columns with no relevance

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [26]:
#Label encoding
label_encoder = preprocessing.LabelEncoder()
data['Sex'] = label_encoder.fit_transform(data['Sex'])
data['Embarked'] = label_encoder.fit_transform(data['Embarked'])


In [27]:
#Modelling packages
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## 1. Survival classification

In [64]:
y = data['Survived']
X = data.drop(['Survived'],axis=1)
#Splitting data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
ypred = clf.fit(X_train,y_train).predict(X_test)
ypred
#Model accuracy
print("Accuracy :", accuracy_score(y_test,ypred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y_test,ypred))


Accuracy : 0.7715355805243446
Confusion matrix :
 [[131  26]
 [ 35  75]]


## 2. Pclass classification

In [65]:
y2 = data['Pclass']
X2 = data.drop(['Pclass'],axis=1)
#Splitting data
X2_train,X2_test,y2_train,y2_test = train_test_split(X2,y2,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y2pred = clf.fit(X2_train,y2_train).predict(X2_test)
y2pred
#Model accuracy
print("Accuracy :", accuracy_score(y2_test,y2pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y2_test,y2pred))


Accuracy : 0.5917602996254682
Confusion matrix :
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]


## 3. Sex classification

In [68]:
y3 = data['Sex']
X3 = data.drop(['Sex'],axis=1)
#Splitting data
X3_train,X3_test,y3_train,y3_test = train_test_split(X3,y3,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y3pred = clf.fit(X3_train,y3_train).predict(X3_test)
y3pred
#Model accuracy
print("Accuracy :", accuracy_score(y3_test,y3pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y3_test,y3pred))


Accuracy : 0.7453183520599251
Confusion matrix :
 [[ 49  49]
 [ 19 150]]


## 4. Sex classification

In [70]:
y4 = data['SibSp']
X4 = data.drop(['SibSp'],axis=1)
#Splitting data
X4_train,X4_test,y4_train,y4_test = train_test_split(X4,y4,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y4pred = clf.fit(X4_train,y4_train).predict(X4_test)
y4pred
#Model accuracy
print("Accuracy :", accuracy_score(y4_test,y4pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y4_test,y4pred))


Accuracy : 0.6891385767790262
Confusion matrix :
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]


## 5. Parch classification

In [72]:
y5 = data['Parch']
X5 = data.drop(['Parch'],axis=1)
#Splitting data
X5_train,X5_test,y5_train,y5_test = train_test_split(X5,y5,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y5pred = clf.fit(X5_train,y5_train).predict(X5_test)
y5pred
#Model accuracy
print("Accuracy :", accuracy_score(y5_test,y5pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y5_test,y5pred))


Accuracy : 0.7153558052434457
Confusion matrix :
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]


## 6. Embarked classification

In [71]:
y6 = data['Embarked']
X6 = data.drop(['Embarked'],axis=1)
#Splitting data
X6_train,X6_test,y6_train,y6_test = train_test_split(X6,y6,test_size=0.3,random_state=0)
##Naive Bayes Classification
from sklearn.naive_bayes import *
clf = BernoulliNB()
y6pred = clf.fit(X6_train,y6_train).predict(X6_test)
y6pred
#Model accuracy
print("Accuracy :", accuracy_score(y6_test,y6pred,normalize=True))
print("Confusion matrix :\n", confusion_matrix(y6_test,y6pred))


Accuracy : 0.7340823970037453
Confusion matrix :
 [[  0   0  49]
 [  0   0  22]
 [  0   0 196]]
