In [2]:
import numpy as np
from datetime import date, timedelta

## 1. Create a 3x3x3 array with random values

In [3]:
array = np.random.rand(3,3,3)
array

array([[[0.3067146 , 0.67197835, 0.1150326 ],
        [0.00399969, 0.38191386, 0.40236875],
        [0.5805214 , 0.04734465, 0.28054654]],

       [[0.61705681, 0.73588256, 0.87135855],
        [0.49432347, 0.62274607, 0.39983209],
        [0.59897123, 0.42304146, 0.54699867]],

       [[0.72580541, 0.38961961, 0.51834077],
        [0.03635486, 0.74740596, 0.33833229],
        [0.54286697, 0.10441539, 0.06044858]]])

## 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
array_2 = np.diag(np.arange(4) + 1, k = -1)
array_2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
array_3 = np.tile(np.array([[0,1],[1,0]]), (4,4))
array_3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 4. Normalize a 5x5 random matrix¶

In [10]:
array_4 = np.random.random((5,5))
array_4 = (array_4 - np.mean (array_4)) / (np.std (array_4))
array_4

array([[-0.7968661 , -0.95677081,  1.40429361,  1.16099743, -0.67453878],
       [-0.85950497,  0.2998509 , -1.25738262,  1.36407927, -0.07550964],
       [ 1.6873815 , -1.78915348,  0.36790153,  0.19618242, -1.42380012],
       [-0.0874986 , -1.21050969,  0.80236078,  0.57847046,  0.99077811],
       [-0.23763798, -1.40812053,  0.14643096,  1.081339  ,  0.69722733]])

## 5. How to find common values between two arrays

In [31]:
A = np.random.randint(0,8,8)
B = np.random.randint(0,10,10)
np.intersect1d(A,B)

array([1, 2, 4, 5])

## 6. How to get the dates of yesterday, today and tomorrow?

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print( "Yetserdy  -", yesterday)
print("Today  -" , today)
print("Tomorrow  -", tomorrow)

Yetserdy  - 2020-07-27
Today  - 2020-07-28
Tomorrow  - 2020-07-29


## 7. Consider two random array A and B, check if they are equal

In [25]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Equality = np.array_equal(A, B)
print(f'A:\n{A}\n\n')
print(f'B:\n{B}\n\n')
print(f'Are they equal?: {Equality}')

A:
[[0.48626251 0.88157527 0.70381435]
 [0.24600226 0.8346831  0.28603824]
 [0.10865083 0.37479432 0.5469106 ]]


B:
[[0.56099031 0.62462722 0.01673212]
 [0.16002174 0.59338861 0.82533646]
 [0.70500375 0.941013   0.38882663]]


Are they equal?: False


## 8. Create random vector of size 10 and replace the maximum value by 0

In [23]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.13629329, 0.43698676, 0.37379036, 0.86302446, 0.30109938,
       0.77808743, 0.        , 0.02346267, 0.60151867, 0.05761899])

## 9. How to print all the values of an array?

In [19]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 10. Subtract the mean of each row of a matrix

In [22]:

array = np.random.rand(3,3)
array_mean = array - array.mean(axis=1, keepdims=True)

array_mean

array([[ 0.04531762, -0.45980307,  0.41448545],
       [-0.07894164,  0.16301568, -0.08407403],
       [-0.19958269,  0.41123602, -0.21165333]])

## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?


In [ ]:

arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

## 12. How to get the diagonal of a dot product?

In [36]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([ 6, 36, 53])

## 13. How to find the most frequent value in an array?

In [37]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[5 3 3 1 3 4 3 3 8 6 7 9 9 7 1 3 0 3 5 4]


3

## 14. How to get the n largest values of an array

In [38]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

7

## 15. How to create a record array from a regular array?

In [39]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])